export const thirdPlacePairingSlots = ["1A", "1B", "1D", "1E", "1G", "1I", "1K", "1L"] as const;

export type ThirdPlacePairingSlot = (typeof thirdPlacePairingSlots)[number];

// FIFA World Cup 26 Regulations, Annexe C. Each string maps the slots above,
// in order, to the group of the best third-placed team assigned to that slot.
const fifaThirdPlaceAssignments = [
  "EJIFHGLK", "HGIDJFLK", "EJIDHGLK", "EJIDHFLK", "EGIDJFLK", "EGJDHFLK", "EGIDHFLK", "EGJDHFLI",
  "EGJDHFIK", "HGICJFLK", "EJICHGLK", "EJICHFLK", "EGICJFLK", "EGJCHFLK", "EGICHFLK", "EGJCHFLI",
  "EGJCHFIK", "HGICJDLK", "CJIDHFLK", "CGIDJFLK", "CGJDHFLK", "CGIDHFLK", "CGJDHFLI", "CGJDHFIK",
  "EJICHDLK", "EGICJDLK", "EGJCHDLK", "EGICHDLK", "EGJCHDLI", "EGJCHDIK", "CJEDIFLK", "CJEDHFLK",
  "CEIDHFLK", "CJEDHFLI", "CJEDHFIK", "CGEDJFLK", "CGEDIFLK", "CGEDJFLI", "CGEDJFIK", "CGEDHFLK",
  "CGJDHFLE", "CGJDHFEK", "CGEDHFLI", "CGEDHFIK", "CGJDHFEI", "HJBFIGLK", "EJIBHGLK", "EJBFIHLK",
  "EJBFIGLK", "EJBFHGLK", "EGBFIHLK", "EJBFHGLI", "EJBFHGIK", "HJBDIGLK", "HJBDIFLK", "IGBDJFLK",
  "HGBDJFLK", "HGBDIFLK", "HGBDJFLI", "HGBDJFIK", "EJBDIHLK", "EJBDIGLK", "EJBDHGLK", "EGBDIHLK",
  "EJBDHGLI", "EJBDHGIK", "EJBDIFLK", "EJBDHFLK", "EIBDHFLK", "EJBDHFLI", "EJBDHFIK", "EGBDJFLK",
  "EGBDIFLK", "EGBDJFLI", "EGBDJFIK", "EGBDHFLK", "HGBDJFLE", "HGBDJFEK", "EGBDHFLI", "EGBDHFIK",
  "HGBDJFEI", "HJBCIGLK", "HJBCIFLK", "IGBCJFLK", "HGBCJFLK", "HGBCIFLK", "HGBCJFLI", "HGBCJFIK",
  "EJBCIHLK", "EJBCIGLK", "EJBCHGLK", "EGBCIHLK", "EJBCHGLI", "EJBCHGIK", "EJBCIFLK", "EJBCHFLK",
  "EIBCHFLK", "EJBCHFLI", "EJBCHFIK", "EGBCJFLK", "EGBCIFLK", "EGBCJFLI", "EGBCJFIK", "EGBCHFLK",
  "HGBCJFLE", "HGBCJFEK", "EGBCHFLI", "EGBCHFIK", "HGBCJFEI", "HJBCIDLK", "IGBCJDLK", "HGBCJDLK",
  "HGBCIDLK", "HGBCJDLI", "HGBCJDIK", "CJBDIFLK", "CJBDHFLK", "CIBDHFLK", "CJBDHFLI", "CJBDHFIK",
  "CGBDJFLK", "CGBDIFLK", "CGBDJFLI", "CGBDJFIK", "CGBDHFLK", "CGBDHFLJ", "HGBCJFDK", "CGBDHFLI",
  "CGBDHFIK", "HGBCJFDI", "EJBCIDLK", "EJBCHDLK", "EIBCHDLK", "EJBCHDLI", "EJBCHDIK", "EGBCJDLK",
  "EGBCIDLK", "EGBCJDLI", "EGBCJDIK", "EGBCHDLK", "HGBCJDLE", "HGBCJDEK", "EGBCHDLI", "EGBCHDIK",
  "HGBCJDEI", "CJBDEFLK", "CEBDIFLK", "CJBDEFLI", "CJBDEFIK", "CEBDHFLK", "CJBDHFLE", "CJBDHFEK",
  "CEBDHFLI", "CEBDHFIK", "CJBDHFEI", "CGBDEFLK", "CGBDJFLE", "CGBDJFEK", "CGBDEFLI", "CGBDEFIK",
  "CGBDJFEI", "CGBDHFLE", "CGBDHFEK", "HGBCJFDE", "CGBDHFEI", "HJIFAGLK", "EJIAHGLK", "EJIFAHLK",
  "EJIFAGLK", "EGJFAHLK", "EGIFAHLK", "EGJFAHLI", "EGJFAHIK", "HJIDAGLK", "HJIDAFLK", "IGJDAFLK",
  "HGJDAFLK", "HGIDAFLK", "HGJDAFLI", "HGJDAFIK", "EJIDAHLK", "EJIDAGLK", "EGJDAHLK", "EGIDAHLK",
  "EGJDAHLI", "EGJDAHIK", "EJIDAFLK", "HJEDAFLK", "HEIDAFLK", "HJEDAFLI", "HJEDAFIK", "EGJDAFLK",
  "EGIDAFLK", "EGJDAFLI", "EGJDAFIK", "HGEDAFLK", "HGJDAFLE", "HGJDAFEK", "HGEDAFLI", "HGEDAFIK",
  "HGJDAFEI", "HJICAGLK", "HJICAFLK", "IGJCAFLK", "HGJCAFLK", "HGICAFLK", "HGJCAFLI", "HGJCAFIK",
  "EJICAHLK", "EJICAGLK", "EGJCAHLK", "EGICAHLK", "EGJCAHLI", "EGJCAHIK", "EJICAFLK", "HJECAFLK",
  "HEICAFLK", "HJECAFLI", "HJECAFIK", "EGJCAFLK", "EGICAFLK", "EGJCAFLI", "EGJCAFIK", "HGECAFLK",
  "HGJCAFLE", "HGJCAFEK", "HGECAFLI", "HGECAFIK", "HGJCAFEI", "HJICADLK", "IGJCADLK", "HGJCADLK",
  "HGICADLK", "HGJCADLI", "HGJCADIK", "CJIDAFLK", "HJFCADLK", "HFICADLK", "HJFCADLI", "HJFCADIK",
  "CGJDAFLK", "CGIDAFLK", "CGJDAFLI", "CGJDAFIK", "HGFCADLK", "CGJDAFLH", "HGJCAFDK", "HGFCADLI",
  "HGFCADIK", "HGJCAFDI", "EJICADLK", "HJECADLK", "HEICADLK", "HJECADLI", "HJECADIK", "EGJCADLK",
  "EGICADLK", "EGJCADLI", "EGJCADIK", "HGECADLK", "HGJCADLE", "HGJCADEK", "HGECADLI", "HGECADIK",
  "HGJCADEI", "CJEDAFLK", "CEIDAFLK", "CJEDAFLI", "CJEDAFIK", "HEFCADLK", "HJFCADLE", "HJECAFDK",
  "HEFCADLI", "HEFCADIK", "HJECAFDI", "CGEDAFLK", "CGJDAFLE", "CGJDAFEK", "CGEDAFLI", "CGEDAFIK",
  "CGJDAFEI", "HGFCADLE", "HGECAFDK", "HGJCAFDE", "HGECAFDI", "HJBAIGLK", "HJBAIFLK", "IJBFAGLK",
  "HJBFAGLK", "HGBAIFLK", "HJBFAGLI", "HJBFAGIK", "EJBAIHLK", "EJBAIGLK", "EJBAHGLK", "EGBAIHLK",
  "EJBAHGLI", "EJBAHGIK", "EJBAIFLK", "EJBFAHLK", "EIBFAHLK", "EJBFAHLI", "EJBFAHIK", "EJBFAGLK",
  "EGBAIFLK", "EJBFAGLI", "EJBFAGIK", "EGBFAHLK", "HJBFAGLE", "HJBFAGEK", "EGBFAHLI", "EGBFAHIK",
  "HJBFAGEI", "IJBDAHLK", "IJBDAGLK", "HJBDAGLK", "IGBDAHLK", "HJBDAGLI", "HJBDAGIK", "IJBDAFLK",
  "HJBDAFLK", "HIBDAFLK", "HJBDAFLI", "HJBDAFIK", "FJBDAGLK", "IGBDAFLK", "FJBDAGLI", "FJBDAGIK",
  "HGBDAFLK", "HGBDAFLJ", "HGBDAFJK", "HGBDAFLI", "HGBDAFIK", "HGBDAFIJ", "EJBAIDLK", "EJBDAHLK",
  "EIBDAHLK", "EJBDAHLI", "EJBDAHIK", "EJBDAGLK", "EGBAIDLK", "EJBDAGLI", "EJBDAGIK", "EGBDAHLK",
  "HJBDAGLE", "HJBDAGEK", "EGBDAHLI", "EGBDAHIK", "HJBDAGEI", "EJBDAFLK", "EIBDAFLK", "EJBDAFLI",
  "EJBDAFIK", "HEBDAFLK", "HJBDAFLE", "HJBDAFEK", "HEBDAFLI", "HEBDAFIK", "HJBDAFEI", "EGBDAFLK",
  "EGBDAFLJ", "EGBDAFJK", "EGBDAFLI", "EGBDAFIK", "EGBDAFIJ", "HGBDAFLE", "HGBDAFEK", "HGBDAFEJ",
  "HGBDAFEI", "IJBCAHLK", "IJBCAGLK", "HJBCAGLK", "IGBCAHLK", "HJBCAGLI", "HJBCAGIK", "IJBCAFLK",
  "HJBCAFLK", "HIBCAFLK", "HJBCAFLI", "HJBCAFIK", "CJBFAGLK", "IGBCAFLK", "CJBFAGLI", "CJBFAGIK",
  "HGBCAFLK", "HGBCAFLJ", "HGBCAFJK", "HGBCAFLI", "HGBCAFIK", "HGBCAFIJ", "EJBAICLK", "EJBCAHLK",
  "EIBCAHLK", "EJBCAHLI", "EJBCAHIK", "EJBCAGLK", "EGBAICLK", "EJBCAGLI", "EJBCAGIK", "EGBCAHLK",
  "HJBCAGLE", "HJBCAGEK", "EGBCAHLI", "EGBCAHIK", "HJBCAGEI", "EJBCAFLK", "EIBCAFLK", "EJBCAFLI",
  "EJBCAFIK", "HEBCAFLK", "HJBCAFLE", "HJBCAFEK", "HEBCAFLI", "HEBCAFIK", "HJBCAFEI", "EGBCAFLK",
  "EGBCAFLJ", "EGBCAFJK", "EGBCAFLI", "EGBCAFIK", "EGBCAFIJ", "HGBCAFLE", "HGBCAFEK", "HGBCAFEJ",
  "HGBCAFEI", "IJBCADLK", "HJBCADLK", "HIBCADLK", "HJBCADLI", "HJBCADIK", "CJBDAGLK", "IGBCADLK",
  "CJBDAGLI", "CJBDAGIK", "HGBCADLK", "HGBCADLJ", "HGBCADJK", "HGBCADLI", "HGBCADIK", "HGBCADIJ",
  "CJBDAFLK", "CIBDAFLK", "CJBDAFLI", "CJBDAFIK", "HFBCADLK", "CJBDAFLH", "HJBCAFDK", "HFBCADLI",
  "HFBCADIK", "HJBCAFDI", "CGBDAFLK", "CGBDAFLJ", "CGBDAFJK", "CGBDAFLI", "CGBDAFIK", "CGBDAFIJ",
  "CGBDAFLH", "HGBCAFDK", "HGBCAFDJ", "HGBCAFDI", "EJBCADLK", "EIBCADLK", "EJBCADLI", "EJBCADIK",
  "HEBCADLK", "HJBCADLE", "HJBCADEK", "HEBCADLI", "HEBCADIK", "HJBCADEI", "EGBCADLK", "EGBCADLJ",
  "EGBCADJK", "EGBCADLI", "EGBCADIK", "EGBCADIJ", "HGBCADLE", "HGBCADEK", "HGBCADEJ", "HGBCADEI",
  "CEBDAFLK", "CJBDAFLE", "CJBDAFEK", "CEBDAFLI", "CEBDAFIK", "CJBDAFEI", "HFBCADLE", "HEBCAFDK",
  "HJBCAFDE", "HEBCAFDI", "CGBDAFLE", "CGBDAFEK", "CGBDAFEJ", "CGBDAFEI", "HGBCAFDE",
] as const;

const validGroupLetters = new Set("ABCDEFGHIJKL".split(""));

const pairingByQualifiedGroups = new Map(
  fifaThirdPlaceAssignments.map((assignment) => {
    const key = assignment.split("").sort().join("");
    const value = Object.fromEntries(
      thirdPlacePairingSlots.map((slot, index) => [slot, assignment[index]]),
    ) as Record<ThirdPlacePairingSlot, string>;

    return [key, value] as const;
  }),
);

export function getThirdPlacePairing(qualifiedGroupLetters: string[]) {
  const normalized = [...new Set(qualifiedGroupLetters.map((letter) => letter.toUpperCase()))]
    .filter((letter) => validGroupLetters.has(letter))
    .sort();

  if (normalized.length !== 8) {
    return null;
  }

  return pairingByQualifiedGroups.get(normalized.join("")) ?? null;
}
